import { createClient } from "@/lib/supabase/server";
import { NextRequest, NextResponse } from "next/server";
import type { ReportType, DevKit } from "@/lib/types";
import { logActivity } from "@/lib/activity-logger";

interface TaskWithProfile {
  id: string;
  title: string;
  status: string;
  priority: string;
  due_date: string | null;
  client_id: string | null;
  profiles: { name: string } | null;
}

interface ClientRow {
  id: string;
  name: string;
  company: string | null;
  health_score: number;
  status: string;
}

interface AlertRow {
  id: string;
  type: string;
  title: string;
  message: string | null;
  severity: string;
  is_resolved: boolean;
}

interface ProjectRow {
  id: string;
  name: string;
  status: string;
  due_date: string | null;
}

interface ProfileRow {
  id: string;
  name: string;
  email: string;
  role: string;
}

interface ReportTheme {
  colorBackground: string;
  colorPrimary: string;
  colorSurface: string;
  colorText: string;
  fontHeading: string;
  fontBody: string;
}

const DEFAULT_THEME: ReportTheme = {
  colorBackground: "#0a0a0a",
  colorPrimary: "#6366f1",
  colorSurface: "rgba(255,255,255,0.05)",
  colorText: "#f1f1f1",
  fontHeading: "'Inter', -apple-system, sans-serif",
  fontBody: "'Inter', -apple-system, sans-serif",
};

function themeFromDevKit(devKit: DevKit): ReportTheme {
  return {
    colorBackground: devKit.color_background,
    colorPrimary: devKit.color_primary,
    colorSurface: devKit.color_surface,
    colorText: devKit.color_text,
    fontHeading: `'${devKit.font_heading}', -apple-system, sans-serif`,
    fontBody: `'${devKit.font_body}', -apple-system, sans-serif`,
  };
}

function htmlShell(title: string, bodyContent: string, theme: ReportTheme = DEFAULT_THEME): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: ${theme.fontBody};
    background: ${theme.colorBackground};
    color: ${theme.colorText};
    padding: 2rem;
    line-height: 1.6;
  }
  .container { max-width: 960px; margin: 0 auto; }
  .header {
    border-bottom: 2px solid ${theme.colorPrimary};
    padding-bottom: 1rem;
    margin-bottom: 2rem;
  }
  .header h1 { font-family: ${theme.fontHeading}; font-size: 1.75rem; font-weight: 700; color: #fff; }
  .header .meta { font-size: 0.85rem; color: #9ca3af; margin-top: 0.25rem; }
  .section { margin-bottom: 2rem; }
  .section h2 {
    font-family: ${theme.fontHeading};
    font-size: 1.15rem;
    font-weight: 600;
    color: ${theme.colorPrimary};
    margin-bottom: 0.75rem;
    border-left: 3px solid ${theme.colorPrimary};
    padding-left: 0.75rem;
  }
  table { width: 100%; border-collapse: collapse; }
  th, td {
    text-align: left;
    padding: 0.6rem 0.75rem;
    border-bottom: 1px solid rgba(255,255,255,0.08);
    font-size: 0.9rem;
  }
  th { color: #9ca3af; font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }
  .badge {
    display: inline-block;
    padding: 0.15rem 0.5rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 500;
  }
  .badge-high, .badge-urgent { background: rgba(239,68,68,0.15); color: #ef4444; }
  .badge-medium { background: rgba(234,179,8,0.15); color: #eab308; }
  .badge-low { background: rgba(34,197,94,0.15); color: #22c55e; }
  .badge-pending, .badge-in_progress { background: rgba(59,130,246,0.15); color: #3b82f6; }
  .badge-completed { background: rgba(34,197,94,0.15); color: #22c55e; }
  .badge-blocked { background: rgba(239,68,68,0.15); color: #ef4444; }
  .badge-active { background: rgba(34,197,94,0.15); color: #22c55e; }
  .badge-critical { background: rgba(239,68,68,0.2); color: #fca5a5; }
  .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; }
  .stat-card {
    background: ${theme.colorSurface};
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 0.75rem;
    padding: 1.25rem;
  }
  .stat-card .label { font-size: 0.8rem; color: #9ca3af; }
  .stat-card .value { font-size: 1.5rem; font-weight: 700; color: #fff; margin-top: 0.25rem; }
  .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid rgba(255,255,255,0.08); font-size: 0.75rem; color: #6b7280; text-align: center; }
  .health-bar { height: 6px; border-radius: 3px; background: rgba(255,255,255,0.1); overflow: hidden; }
  .health-fill { height: 100%; border-radius: 3px; }
  .empty { color: #6b7280; font-style: italic; padding: 1rem 0; }
</style>
</head>
<body>
<div class="container">
${bodyContent}
<div class="footer">Generated by SUMAIT Command Center &mdash; ${new Date().toISOString()}</div>
</div>
</body>
</html>`;
}

function healthColor(score: number): string {
  if (score >= 70) return "#22c55e";
  if (score >= 40) return "#eab308";
  return "#ef4444";
}

function generateMorningBriefHTML(
  title: string,
  tasks: TaskWithProfile[],
  alerts: AlertRow[],
  clients: ClientRow[],
  theme: ReportTheme = DEFAULT_THEME
): string {
  const pending = tasks.filter((t) => t.status === "pending");
  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const blocked = tasks.filter((t) => t.status === "blocked");

  const body = `
<div class="header">
  <h1>${title}</h1>
  <div class="meta">Daily overview of operations, tasks, and alerts</div>
</div>

<div class="section">
  <div class="stat-grid">
    <div class="stat-card"><div class="label">Active Tasks</div><div class="value">${tasks.length}</div></div>
    <div class="stat-card"><div class="label">Pending</div><div class="value">${pending.length}</div></div>
    <div class="stat-card"><div class="label">In Progress</div><div class="value">${inProgress.length}</div></div>
    <div class="stat-card"><div class="label">Blocked</div><div class="value">${blocked.length}</div></div>
    <div class="stat-card"><div class="label">Active Alerts</div><div class="value">${alerts.length}</div></div>
    <div class="stat-card"><div class="label">Active Clients</div><div class="value">${clients.length}</div></div>
  </div>
</div>

${alerts.length > 0 ? `
<div class="section">
  <h2>Unresolved Alerts</h2>
  <table>
    <thead><tr><th>Alert</th><th>Severity</th><th>Message</th></tr></thead>
    <tbody>
      ${alerts.map((a) => `<tr><td>${a.title}</td><td><span class="badge badge-${a.severity}">${a.severity}</span></td><td>${a.message || "-"}</td></tr>`).join("")}
    </tbody>
  </table>
</div>` : ""}

<div class="section">
  <h2>Tasks Requiring Attention</h2>
  ${tasks.length === 0 ? '<p class="empty">No active tasks.</p>' : `
  <table>
    <thead><tr><th>Task</th><th>Status</th><th>Priority</th><th>Assigned To</th><th>Due Date</th></tr></thead>
    <tbody>
      ${tasks.map((t) => `<tr>
        <td>${t.title}</td>
        <td><span class="badge badge-${t.status}">${t.status.replace("_", " ")}</span></td>
        <td><span class="badge badge-${t.priority}">${t.priority}</span></td>
        <td>${t.profiles?.name || "Unassigned"}</td>
        <td>${t.due_date || "-"}</td>
      </tr>`).join("")}
    </tbody>
  </table>`}
</div>

<div class="section">
  <h2>Client Health Overview</h2>
  ${clients.length === 0 ? '<p class="empty">No active clients.</p>' : `
  <table>
    <thead><tr><th>Client</th><th>Health</th><th>Score</th></tr></thead>
    <tbody>
      ${clients.map((c) => `<tr>
        <td>${c.name}</td>
        <td><div class="health-bar" style="width:120px"><div class="health-fill" style="width:${c.health_score}%;background:${healthColor(c.health_score)}"></div></div></td>
        <td>${c.health_score}/100</td>
      </tr>`).join("")}
    </tbody>
  </table>`}
</div>`;

  return htmlShell(title, body, theme);
}

function generateClientReportHTML(
  title: string,
  client: ClientRow | null,
  projects: ProjectRow[],
  tasks: TaskWithProfile[],
  theme: ReportTheme = DEFAULT_THEME
): string {
  if (!client) {
    return htmlShell(title, '<p class="empty">Client not found.</p>', theme);
  }

  const completed = tasks.filter((t) => t.status === "completed").length;
  const total = tasks.length;

  const body = `
<div class="header">
  <h1>${title}</h1>
  <div class="meta">Detailed report for ${client.company || client.name}</div>
</div>

<div class="section">
  <div class="stat-grid">
    <div class="stat-card"><div class="label">Health Score</div><div class="value" style="color:${healthColor(client.health_score)}">${client.health_score}</div></div>
    <div class="stat-card"><div class="label">Status</div><div class="value" style="text-transform:capitalize">${client.status}</div></div>
    <div class="stat-card"><div class="label">Projects</div><div class="value">${projects.length}</div></div>
    <div class="stat-card"><div class="label">Tasks Done</div><div class="value">${completed}/${total}</div></div>
  </div>
</div>

<div class="section">
  <h2>Projects</h2>
  ${projects.length === 0 ? '<p class="empty">No projects.</p>' : `
  <table>
    <thead><tr><th>Project</th><th>Status</th><th>Due Date</th></tr></thead>
    <tbody>
      ${projects.map((p) => `<tr>
        <td>${p.name}</td>
        <td><span class="badge badge-${p.status}">${p.status.replace("_", " ")}</span></td>
        <td>${p.due_date || "-"}</td>
      </tr>`).join("")}
    </tbody>
  </table>`}
</div>

<div class="section">
  <h2>Tasks</h2>
  ${tasks.length === 0 ? '<p class="empty">No tasks.</p>' : `
  <table>
    <thead><tr><th>Task</th><th>Status</th><th>Priority</th><th>Assigned To</th></tr></thead>
    <tbody>
      ${tasks.map((t) => `<tr>
        <td>${t.title}</td>
        <td><span class="badge badge-${t.status}">${t.status.replace("_", " ")}</span></td>
        <td><span class="badge badge-${t.priority}">${t.priority}</span></td>
        <td>${t.profiles?.name || "Unassigned"}</td>
      </tr>`).join("")}
    </tbody>
  </table>`}
</div>`;

  return htmlShell(title, body, theme);
}

function generateEmployeeReportHTML(
  title: string,
  employee: ProfileRow | null,
  tasks: TaskWithProfile[],
  theme: ReportTheme = DEFAULT_THEME
): string {
  if (!employee) {
    return htmlShell(title, '<p class="empty">Employee not found.</p>', theme);
  }

  const completed = tasks.filter((t) => t.status === "completed").length;
  const pending = tasks.filter((t) => t.status === "pending").length;
  const inProgress = tasks.filter((t) => t.status === "in_progress").length;

  const body = `
<div class="header">
  <h1>${title}</h1>
  <div class="meta">Performance and task report for ${employee.name}</div>
</div>

<div class="section">
  <div class="stat-grid">
    <div class="stat-card"><div class="label">Total Tasks</div><div class="value">${tasks.length}</div></div>
    <div class="stat-card"><div class="label">Completed</div><div class="value" style="color:#22c55e">${completed}</div></div>
    <div class="stat-card"><div class="label">In Progress</div><div class="value" style="color:#3b82f6">${inProgress}</div></div>
    <div class="stat-card"><div class="label">Pending</div><div class="value" style="color:#eab308">${pending}</div></div>
  </div>
</div>

<div class="section">
  <h2>Task Breakdown</h2>
  ${tasks.length === 0 ? '<p class="empty">No tasks assigned.</p>' : `
  <table>
    <thead><tr><th>Task</th><th>Status</th><th>Priority</th><th>Due Date</th></tr></thead>
    <tbody>
      ${tasks.map((t) => `<tr>
        <td>${t.title}</td>
        <td><span class="badge badge-${t.status}">${t.status.replace("_", " ")}</span></td>
        <td><span class="badge badge-${t.priority}">${t.priority}</span></td>
        <td>${t.due_date || "-"}</td>
      </tr>`).join("")}
    </tbody>
  </table>`}
</div>`;

  return htmlShell(title, body, theme);
}

function generateTeamPerformanceHTML(
  title: string,
  members: ProfileRow[],
  tasks: TaskWithProfile[],
  theme: ReportTheme = DEFAULT_THEME
): string {
  const memberStats = members.map((m) => {
    const memberTasks = tasks.filter((t) => t.profiles?.name === m.name);
    const completed = memberTasks.filter((t) => t.status === "completed").length;
    return { ...m, total: memberTasks.length, completed };
  });

  const body = `
<div class="header">
  <h1>${title}</h1>
  <div class="meta">Team-wide performance overview</div>
</div>

<div class="section">
  <div class="stat-grid">
    <div class="stat-card"><div class="label">Team Members</div><div class="value">${members.length}</div></div>
    <div class="stat-card"><div class="label">Total Tasks</div><div class="value">${tasks.length}</div></div>
    <div class="stat-card"><div class="label">Completed</div><div class="value" style="color:#22c55e">${tasks.filter((t) => t.status === "completed").length}</div></div>
    <div class="stat-card"><div class="label">Completion Rate</div><div class="value">${tasks.length > 0 ? Math.round((tasks.filter((t) => t.status === "completed").length / tasks.length) * 100) : 0}%</div></div>
  </div>
</div>

<div class="section">
  <h2>Member Performance</h2>
  ${memberStats.length === 0 ? '<p class="empty">No team members.</p>' : `
  <table>
    <thead><tr><th>Member</th><th>Role</th><th>Total Tasks</th><th>Completed</th><th>Rate</th></tr></thead>
    <tbody>
      ${memberStats.map((m) => `<tr>
        <td>${m.name}</td>
        <td style="text-transform:capitalize">${m.role}</td>
        <td>${m.total}</td>
        <td>${m.completed}</td>
        <td>${m.total > 0 ? Math.round((m.completed / m.total) * 100) : 0}%</td>
      </tr>`).join("")}
    </tbody>
  </table>`}
</div>`;

  return htmlShell(title, body, theme);
}

function generateDelegationDashboardHTML(
  title: string,
  members: ProfileRow[],
  tasks: TaskWithProfile[],
  theme: ReportTheme = DEFAULT_THEME
): string {
  const unassigned = tasks.filter((t) => !t.profiles);
  const memberLoad = members.map((m) => {
    const memberTasks = tasks.filter((t) => t.profiles?.name === m.name);
    return { ...m, tasks: memberTasks };
  });

  const body = `
<div class="header">
  <h1>${title}</h1>
  <div class="meta">Task delegation and workload distribution overview</div>
</div>

<div class="section">
  <div class="stat-grid">
    <div class="stat-card"><div class="label">Active Tasks</div><div class="value">${tasks.length}</div></div>
    <div class="stat-card"><div class="label">Unassigned</div><div class="value" style="color:#ef4444">${unassigned.length}</div></div>
    <div class="stat-card"><div class="label">Team Members</div><div class="value">${members.length}</div></div>
  </div>
</div>

${unassigned.length > 0 ? `
<div class="section">
  <h2>Unassigned Tasks</h2>
  <table>
    <thead><tr><th>Task</th><th>Priority</th><th>Due Date</th></tr></thead>
    <tbody>
      ${unassigned.map((t) => `<tr>
        <td>${t.title}</td>
        <td><span class="badge badge-${t.priority}">${t.priority}</span></td>
        <td>${t.due_date || "-"}</td>
      </tr>`).join("")}
    </tbody>
  </table>
</div>` : ""}

<div class="section">
  <h2>Workload by Team Member</h2>
  ${memberLoad.map((m) => `
  <div style="margin-bottom:1.5rem">
    <h3 style="color:#e5e7eb;font-size:0.95rem;margin-bottom:0.5rem">${m.name} <span style="color:#9ca3af;font-weight:400">(${m.tasks.length} tasks)</span></h3>
    ${m.tasks.length === 0 ? '<p class="empty" style="padding:0.25rem 0">No tasks assigned.</p>' : `
    <table>
      <thead><tr><th>Task</th><th>Status</th><th>Priority</th></tr></thead>
      <tbody>
        ${m.tasks.map((t) => `<tr>
          <td>${t.title}</td>
          <td><span class="badge badge-${t.status}">${t.status.replace("_", " ")}</span></td>
          <td><span class="badge badge-${t.priority}">${t.priority}</span></td>
        </tr>`).join("")}
      </tbody>
    </table>`}
  </div>`).join("")}
</div>`;

  return htmlShell(title, body, theme);
}

interface DailyReportRow {
  id: string;
  user_id: string;
  report_date: string;
  created_at: string;
  profiles: { name: string } | null;
}

interface DailyReportItemRow {
  id: string;
  report_id: string;
  item_type: "completed" | "pending" | "blocker";
  description: string;
  links: string[];
  sort_order: number;
}

interface DailyReportAttachmentRow {
  id: string;
  item_id: string;
  report_id: string;
  file_name: string;
}

function generateDelegationDailyHTML(
  title: string,
  reports: DailyReportRow[],
  items: DailyReportItemRow[],
  attachments: DailyReportAttachmentRow[],
  theme: ReportTheme = DEFAULT_THEME
): string {
  const completedItems = items.filter((i) => i.item_type === "completed");
  const pendingItems = items.filter((i) => i.item_type === "pending");
  const blockerItems = items.filter((i) => i.item_type === "blocker");

  const builderMap = new Map<string, { name: string; reportIds: string[] }>();
  for (const r of reports) {
    const name = r.profiles?.name || "Unknown";
    const existing = builderMap.get(r.user_id);
    if (existing) {
      existing.reportIds.push(r.id);
    } else {
      builderMap.set(r.user_id, { name, reportIds: [r.id] });
    }
  }

  const builderSections = Array.from(builderMap.entries())
    .map(([, builder]) => {
      const reportIds = new Set(builder.reportIds);
      const builderItems = items.filter((i) => reportIds.has(i.report_id));
      const completed = builderItems.filter((i) => i.item_type === "completed");
      const pending = builderItems.filter((i) => i.item_type === "pending");
      const blockers = builderItems.filter((i) => i.item_type === "blocker");
      const builderAttachments = attachments.filter((a) => reportIds.has(a.report_id));

      const renderItems = (list: DailyReportItemRow[]) =>
        list.length === 0
          ? '<p class="empty" style="padding:0.25rem 0">None</p>'
          : `<ul style="list-style:disc;padding-left:1.25rem;margin:0">${list
              .sort((a, b) => a.sort_order - b.sort_order)
              .map((i) => {
                const itemAttachments = builderAttachments.filter((a) => a.item_id === i.id);
                const attachLabel =
                  itemAttachments.length > 0
                    ? ` <span style="color:#9ca3af;font-size:0.8rem">[${itemAttachments.map((a) => a.file_name).join(", ")}]</span>`
                    : "";
                const linkLabel =
                  i.links && i.links.length > 0
                    ? ` <span style="color:#9ca3af;font-size:0.8rem">(${i.links.length} link${i.links.length > 1 ? "s" : ""})</span>`
                    : "";
                return `<li style="margin-bottom:0.35rem">${i.description}${linkLabel}${attachLabel}</li>`;
              })
              .join("")}</ul>`;

      return `
    <div style="margin-bottom:2rem;padding:1.25rem;background:${theme.colorSurface};border:1px solid rgba(255,255,255,0.1);border-radius:0.75rem">
      <h3 style="color:#e5e7eb;font-size:1rem;font-weight:600;margin-bottom:1rem;font-family:${theme.fontHeading}">${builder.name} <span style="color:#9ca3af;font-weight:400;font-size:0.85rem">(${builderItems.length} items)</span></h3>
      <div style="margin-bottom:0.75rem">
        <h4 style="color:#22c55e;font-size:0.85rem;font-weight:600;margin-bottom:0.35rem">Completed (${completed.length})</h4>
        ${renderItems(completed)}
      </div>
      <div style="margin-bottom:0.75rem">
        <h4 style="color:#eab308;font-size:0.85rem;font-weight:600;margin-bottom:0.35rem">Pending (${pending.length})</h4>
        ${renderItems(pending)}
      </div>
      ${blockers.length > 0 ? `
      <div>
        <h4 style="color:#ef4444;font-size:0.85rem;font-weight:600;margin-bottom:0.35rem">Blockers (${blockers.length})</h4>
        ${renderItems(blockers)}
      </div>` : ""}
    </div>`;
    })
    .join("");

  const body = `
<div class="header">
  <h1>${title}</h1>
  <div class="meta">Daily delegation report &mdash; builder submissions overview</div>
</div>

<div class="section">
  <div class="stat-grid">
    <div class="stat-card"><div class="label">Reports</div><div class="value">${reports.length}</div></div>
    <div class="stat-card"><div class="label">Builders</div><div class="value">${builderMap.size}</div></div>
    <div class="stat-card"><div class="label">Total Items</div><div class="value">${items.length}</div></div>
    <div class="stat-card"><div class="label">Completed</div><div class="value" style="color:#22c55e">${completedItems.length}</div></div>
    <div class="stat-card"><div class="label">Pending</div><div class="value" style="color:#eab308">${pendingItems.length}</div></div>
    <div class="stat-card"><div class="label">Blockers</div><div class="value" style="color:#ef4444">${blockerItems.length}</div></div>
  </div>
</div>

<div class="section">
  <h2>Builder Breakdown</h2>
  ${reports.length === 0 ? '<p class="empty">No daily reports found for this period.</p>' : builderSections}
</div>`;

  return htmlShell(title, body, theme);
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const body = await request.json();
    const type = body.type as ReportType;
    const parameters = body.parameters || {};
    const devKitId: string | null = body.devKitId || null;

    if (!type) {
      return NextResponse.json({ error: "Report type is required" }, { status: 400 });
    }

    let theme = DEFAULT_THEME;
    if (devKitId) {
      const { data: devKit } = await supabase
        .from("dev_kits")
        .select("*")
        .eq("id", devKitId)
        .single();
      if (devKit) {
        theme = themeFromDevKit(devKit as DevKit);
      }
    }

    let html = "";
    let title = "";

    switch (type) {
      case "morning_brief": {
        title = `Morning Brief - ${parameters.date || new Date().toISOString().split("T")[0]}`;
        const { data: tasks } = await supabase
          .from("tasks")
          .select("id, title, status, priority, due_date, client_id, profiles:assigned_to(name)")
          .in("status", ["pending", "in_progress", "blocked"])
          .limit(500);
        const { data: alerts } = await supabase
          .from("alerts")
          .select("*")
          .eq("is_resolved", false);
        const { data: clients } = await supabase
          .from("clients")
          .select("*")
          .eq("status", "active");
        html = generateMorningBriefHTML(
          title,
          (tasks as unknown as TaskWithProfile[]) || [],
          (alerts as AlertRow[]) || [],
          (clients as ClientRow[]) || [],
          theme
        );
        break;
      }

      case "client_report": {
        if (!parameters.clientId) {
          return NextResponse.json({ error: "Client ID is required" }, { status: 400 });
        }
        const { data: client } = await supabase
          .from("clients")
          .select("*")
          .eq("id", parameters.clientId)
          .single();
        const { data: projects } = await supabase
          .from("projects")
          .select("id, name, status, due_date")
          .eq("client_id", parameters.clientId);
        const { data: tasks } = await supabase
          .from("tasks")
          .select("id, title, status, priority, due_date, client_id, profiles:assigned_to(name)")
          .eq("client_id", parameters.clientId)
          .limit(500);
        title = `Client Report - ${client?.name || "Unknown"}`;
        html = generateClientReportHTML(
          title,
          client as ClientRow | null,
          (projects as ProjectRow[]) || [],
          (tasks as unknown as TaskWithProfile[]) || [],
          theme
        );
        break;
      }

      case "employee_report": {
        if (!parameters.employeeId) {
          return NextResponse.json({ error: "Employee ID is required" }, { status: 400 });
        }
        const { data: employee } = await supabase
          .from("profiles")
          .select("id, name, email, role")
          .eq("id", parameters.employeeId)
          .single();
        const { data: tasks } = await supabase
          .from("tasks")
          .select("id, title, status, priority, due_date, client_id, profiles:assigned_to(name)")
          .eq("assigned_to", parameters.employeeId)
          .limit(500);
        title = `Employee Report - ${employee?.name || "Unknown"}`;
        html = generateEmployeeReportHTML(
          title,
          employee as ProfileRow | null,
          (tasks as unknown as TaskWithProfile[]) || [],
          theme
        );
        break;
      }

      case "team_performance": {
        const startDate = parameters.startDate || "";
        const endDate = parameters.endDate || "";
        title = `Team Performance${startDate ? ` (${startDate} to ${endDate})` : ""}`;
        const { data: members } = await supabase
          .from("profiles")
          .select("id, name, email, role")
          .eq("is_active", true);
        let tasksQuery = supabase
          .from("tasks")
          .select("id, title, status, priority, due_date, client_id, profiles:assigned_to(name)");
        if (startDate) tasksQuery = tasksQuery.gte("created_at", startDate);
        if (endDate) tasksQuery = tasksQuery.lte("created_at", endDate + "T23:59:59");
        const { data: tasks } = await tasksQuery.limit(500);
        html = generateTeamPerformanceHTML(
          title,
          (members as ProfileRow[]) || [],
          (tasks as unknown as TaskWithProfile[]) || [],
          theme
        );
        break;
      }

      case "delegation_dashboard": {
        title = "Delegation Dashboard";
        const { data: members } = await supabase
          .from("profiles")
          .select("id, name, email, role")
          .eq("is_active", true);
        const { data: tasks } = await supabase
          .from("tasks")
          .select("id, title, status, priority, due_date, client_id, profiles:assigned_to(name)")
          .neq("status", "completed")
          .limit(500);
        html = generateDelegationDashboardHTML(
          title,
          (members as ProfileRow[]) || [],
          (tasks as unknown as TaskWithProfile[]) || [],
          theme
        );
        break;
      }

      case "delegation_daily": {
        const scope: string = parameters.scope || "daily";
        const singleDate = parameters.date || new Date().toISOString().split("T")[0];
        const dateStart = scope === "weekly" ? parameters.dateStart || singleDate : singleDate;
        const dateEnd = scope === "weekly" ? parameters.dateEnd || singleDate : singleDate;

        title = scope === "weekly"
          ? `Delegation Report (${dateStart} to ${dateEnd})`
          : `Delegation Report - ${singleDate}`;

        let reportsQuery = supabase
          .from("daily_reports")
          .select("id, user_id, report_date, created_at, profiles:user_id(name)")
          .gte("report_date", dateStart)
          .lte("report_date", dateEnd)
          .order("report_date", { ascending: true });

        if (parameters.userId) {
          reportsQuery = reportsQuery.eq("user_id", parameters.userId);
        }

        const { data: dailyReports } = await reportsQuery;
        const reportRows = (dailyReports as unknown as DailyReportRow[]) || [];
        const reportIds = reportRows.map((r) => r.id);

        let itemRows: DailyReportItemRow[] = [];
        let attachmentRows: DailyReportAttachmentRow[] = [];

        if (reportIds.length > 0) {
          const { data: fetchedItems } = await supabase
            .from("daily_report_items")
            .select("id, report_id, item_type, description, links, sort_order")
            .in("report_id", reportIds)
            .order("sort_order", { ascending: true });
          itemRows = (fetchedItems as DailyReportItemRow[]) || [];

          const { data: fetchedAttachments } = await supabase
            .from("daily_report_attachments")
            .select("id, item_id, report_id, file_name")
            .in("report_id", reportIds);
          attachmentRows = (fetchedAttachments as DailyReportAttachmentRow[]) || [];
        }

        html = generateDelegationDailyHTML(title, reportRows, itemRows, attachmentRows, theme);
        break;
      }

      default:
        return NextResponse.json({ error: "Invalid report type" }, { status: 400 });
    }

    const { data: { user } } = await supabase.auth.getUser();

    const storageType = type === "delegation_daily" ? "delegation_dashboard" : type;

    const { data: report, error } = await supabase
      .from("generated_reports")
      .insert({
        type: storageType,
        title,
        parameters,
        html_content: html,
        dev_kit_id: devKitId,
        generated_by: user?.id || null,
        status: type === "delegation_daily" ? "draft" : undefined,
      })
      .select()
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    await logActivity(supabase, "created", "report", report.id, {
      type: storageType,
      title,
      dev_kit_id: devKitId,
    });

    if (type === "delegation_daily") {
      await logActivity(supabase, "report_generated", "report", report.id, {
        scope: parameters.scope || "daily",
        date_range: { start: parameters.dateStart || parameters.date, end: parameters.dateEnd || parameters.date },
      });
    }

    logActivity(supabase, "report_generated", "generated_report", report.id, { type: report.type }).catch(console.error);

    return NextResponse.json(report);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to generate report";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
